#!/bin/bash

# Helper for searching code base without searching through external code

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd $DIR
    exec ack "$@" $DIR/delfick_project $DIR/tests
)
