#!/bin/bash

# Helper for searching code base without searching through external code

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd "$DIR" || exit 1
    exec ack "$@" \
        --ignore-directory .tox \
        --ignore-directory .mypy_cache \
        --ignore-directory dist \
        --ignore-directory build \
        --ignore-directory tools \
)
